Make crate no_std compatible
hsivonen/encoding_rs pull request #66
Opened 2021-02-03 16:20 UTC by fschutt

- Use BTreeSet instead of HashSet **in tests**, so that tests can run on `no_std`
- Replace all imports of `Vec` and `String` with respective `alloc` types
- `use core::` instead of `use std::`

This is a preparation for https://github.com/yeslogic/allsorts/pull/42, it would be nice if this could get merged so that we can have a proper font shaping library on `no_std`.

2021-02-03 16:22 UTC, fschutt commented
If this gets merged, please publish a new version so I can merge the other PR, thanks

2021-02-04 07:24 UTC, hsivonen requested changes
Thank you! It looks like a global find and replace changed some comments that shouldn't have been changed. Looks good otherwise.

2021-02-04 07:24 UTC, hsivonen commented on src/lib.rs
> +//! # Integration with `core::io`
This bit of find and replace probably shouldn't be here.

2021-02-04 07:24 UTC, hsivonen commented on src/lib.rs
> +//! This crate doesn't implement traits from `core::io`. However, for the case of
Likewise here.

2021-02-04 07:24 UTC, hsivonen commented on src/lib.rs
> +//! let mut buffer: &mut str = core::str::from_utf8_mut(&mut buffer_bytes[..]).unwrap();
And here.

2021-02-04 11:01 UTC, merged

2021-02-04 11:35 UTC, hsivonen commented
I've published a new version with this change to crates.io.